#!/usr/bin/env python3
"""Auto-generate hierarchical INDEX files from YAML source of truth.

Produces:
  - ROOT/INDEX.md            — topic overview / jump page
  - ROOT/topics/<t>/INDEX.md — per-topic detailed node & relation index
  - ROOT/INDEX_metrics.md    — cross-topic metrics quick-reference
  - ROOT/INDEX_principles.md — cross-topic principles quick-reference
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

HEADER = "<!-- AUTO-GENERATED by scripts/build_index.py — DO NOT EDIT MANUALLY -->\n\n"

TOPIC_DISPLAY_NAMES: dict[str, str] = {
    "ultrastable-laser": "Ultrastable Laser",
    "optical-frequency-combs": "Optical Frequency Combs",
    "frequency-standards": "Frequency Standards",
    "timescales": "Timescales",
    "time-frequency-transfer": "Time-Frequency Transfer",
}

TIER_ORDER = ["meta", "foundational", "domain", "engineering"]

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _md_escape(text: str) -> str:
    """Escape pipe and newline characters for markdown table cells."""
    if not isinstance(text, str):
        text = str(text)
    text = text.replace("\n", " ").replace("\r", "")
    text = text.replace("|", "\\|")
    return text.strip()


def _truncate(text: str, max_len: int = 80) -> str:
    text = _md_escape(text)
    if len(text) > max_len:
        return text[: max_len - 1] + "…"
    return text


def _relative_paper_path(yaml_path: Path, repo: Path) -> str:
    """Return e.g. 'topics/ultrastable-laser/papers/matei2017.yaml'."""
    return str(yaml_path.relative_to(repo))


def _paper_label(yaml_path: Path) -> str:
    """Return e.g. 'matei2017'."""
    return yaml_path.stem


def _get_demonstrated_value(metric: dict) -> tuple[str, str]:
    """Return (value_str, conditions_str) from a metric node."""
    dv = metric.get("demonstrated_value")
    if dv is None:
        return ("—", "—")
    if isinstance(dv, dict):
        val = dv.get("value", "—")
        cond = dv.get("conditions", "—")
    else:
        val = str(dv)
        cond = metric.get("conditions", "—")
    return (_truncate(str(val), 100), _truncate(str(cond), 80))


# ---------------------------------------------------------------------------
# YAML loading
# ---------------------------------------------------------------------------


def load_all_papers(repo: Path) -> list[dict[str, Any]]:
    """Load every topics/*/papers/*.yaml and attach file metadata."""
    results: list[dict[str, Any]] = []
    topics_dir = repo / "topics"
    if not topics_dir.is_dir():
        return results
    for yaml_path in sorted(topics_dir.glob("*/papers/*.yaml")):
        try:
            with yaml_path.open("r", encoding="utf-8") as fh:
                data = yaml.safe_load(fh)
        except Exception as exc:
            print(f"WARNING: failed to parse {yaml_path}: {exc}", file=sys.stderr)
            continue
        if not isinstance(data, dict):
            continue
        # Infer topic from directory structure
        topic = yaml_path.parent.parent.name
        data.setdefault("meta", {})
        data["meta"].setdefault("topic", topic)
        data["_path"] = yaml_path
        data["_topic"] = topic
        results.append(data)
    return results


def _as_list(section: Any) -> list[dict]:
    """Normalise a YAML section that could be a list or dict-of-dicts."""
    if section is None:
        return []
    if isinstance(section, list):
        return [item for item in section if isinstance(item, dict)]
    if isinstance(section, dict):
        out = []
        for key, val in section.items():
            if isinstance(val, dict):
                val.setdefault("id", key)
                out.append(val)
        return out
    return []


# ---------------------------------------------------------------------------
# Data aggregation
# ---------------------------------------------------------------------------


class TopicData:
    """Aggregated data for one topic."""

    def __init__(self, topic: str):
        self.topic = topic
        self.papers: list[dict] = []
        self.entities: list[tuple[dict, Path]] = []
        self.principles: list[tuple[dict, Path]] = []
        self.methods: list[tuple[dict, Path]] = []
        self.metrics: list[tuple[dict, Path]] = []
        self.relations: list[tuple[dict, Path]] = []

    @property
    def paper_count(self) -> int:
        return len(self.papers)

    @property
    def node_count(self) -> int:
        return (
            len(self.entities)
            + len(self.principles)
            + len(self.methods)
            + len(self.metrics)
        )

    @property
    def relation_count(self) -> int:
        return len(self.relations)


def aggregate(papers: list[dict]) -> dict[str, TopicData]:
    topics: dict[str, TopicData] = {}
    # Ensure all topic dirs are represented even if empty
    for p in papers:
        topic = p["_topic"]
        if topic not in topics:
            topics[topic] = TopicData(topic)
        td = topics[topic]
        td.papers.append(p)
        path = p["_path"]
        for ent in _as_list(p.get("entities")):
            td.entities.append((ent, path))
        for pri in _as_list(p.get("principles")):
            td.principles.append((pri, path))
        for meth in _as_list(p.get("methods")):
            td.methods.append((meth, path))
        for met in _as_list(p.get("metrics")):
            td.metrics.append((met, path))
        for rel in _as_list(p.get("relations")):
            td.relations.append((rel, path))
    return topics


def discover_topic_dirs(repo: Path) -> list[str]:
    """Return all topic directory names, even those with 0 papers."""
    topics_dir = repo / "topics"
    if not topics_dir.is_dir():
        return []
    return sorted(
        d.name
        for d in topics_dir.iterdir()
        if d.is_dir() and (d / "papers").is_dir()
    )


# ---------------------------------------------------------------------------
# Markdown generators
# ---------------------------------------------------------------------------


def _timestamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def build_root_index(
    topics: dict[str, TopicData], all_topic_names: list[str], repo: Path
) -> str:
    lines = [HEADER]
    lines.append("# 📚 sci-logic-kb — Knowledge Base Index\n\n")
    lines.append(f"> Auto-generated {_timestamp()}\n\n")

    # --- By-research-question navigation (static block, preserved across regenerations) ---
    lines.append("## 🧭 按研究问题导航\n\n")
    lines.append(
        "> 如果你是第一次打开这个知识库，建议先从 **研究问题** 而非节点列表入手。"
        "详细指南见 [`docs/USAGE.md`](docs/USAGE.md)。\n\n"
    )
    lines.append("| 我想… | 入口 |\n")
    lines.append("|-------|------|\n")
    lines.append(
        "| 设计一套新的超稳激光装置，选择技术路线 | "
        "[`topics/ultrastable-laser/_meta/architecture.md`](topics/ultrastable-laser/_meta/architecture.md) → "
        "[限制×路径矩阵](topics/ultrastable-laser/synthesis/breakthrough_paths_matrix.md) |\n"
    )
    lines.append(
        "| 诊断我的实验 σ_y 卡在某个数值的瓶颈 | "
        "[`INDEX_metrics.md`](INDEX_metrics.md) → "
        "[误差预算综合页](topics/ultrastable-laser/synthesis/ram_and_pdh_error_budget.md) |\n"
    )
    lines.append(
        "| 了解某个物理分支的历史演化 | "
        "[稳定度时间线](topics/ultrastable-laser/synthesis/stability_record_timeline.md)、"
        "[低温工程路线图](topics/ultrastable-laser/synthesis/cryogenic_roadmap.md)、"
        "[光纤稳频全景](topics/ultrastable-laser/synthesis/fiber_stabilization_landscape.md) |\n"
    )
    lines.append(
        "| 快速掌握专题架构 | "
        "[`TOPICS.md`](TOPICS.md) · 各专题 `_meta/architecture.md` |\n"
    )
    lines.append(
        "| 参与建设 / 贡献论文 | "
        "[`CONTRIBUTING.md`](CONTRIBUTING.md) · [`SCHEMA.md`](SCHEMA.md) |\n"
    )
    lines.append(
        "| 查看待处理工作 | "
        "[`TODO.md`](TODO.md) · [`reports/chain_gap_ultrastable.md`](reports/chain_gap_ultrastable.md) |\n"
    )
    lines.append("\n")

    # --- Topic overview table ---
    lines.append("## Topic Overview\n\n")
    lines.append("| Topic | Papers | Nodes | Relations | Index |\n")
    lines.append("|-------|-------:|------:|----------:|-------|\n")
    total_papers = total_nodes = total_rels = 0
    for t in all_topic_names:
        display = TOPIC_DISPLAY_NAMES.get(t, t)
        td = topics.get(t)
        pc = td.paper_count if td else 0
        nc = td.node_count if td else 0
        rc = td.relation_count if td else 0
        total_papers += pc
        total_nodes += nc
        total_rels += rc
        link = f"[→ INDEX](topics/{t}/INDEX.md)"
        lines.append(f"| {display} | {pc} | {nc} | {rc} | {link} |\n")
    lines.append(f"| **Total** | **{total_papers}** | **{total_nodes}** | **{total_rels}** | |\n")
    lines.append("\n")

    # --- Cross-topic index links ---
    lines.append("## Cross-Topic Quick References\n\n")
    lines.append("| Reference | Description |\n")
    lines.append("|-----------|-------------|\n")
    lines.append("| [INDEX_metrics.md](INDEX_metrics.md) | All metrics with best demonstrated values |\n")
    lines.append("| [INDEX_principles.md](INDEX_principles.md) | All principles grouped by tier |\n")
    lines.append("\n")

    # --- Node type breakdown ---
    lines.append("## Node Breakdown by Type\n\n")
    lines.append("| Topic | Entities | Principles | Methods | Metrics |\n")
    lines.append("|-------|--------:|-----------:|--------:|--------:|\n")
    for t in all_topic_names:
        display = TOPIC_DISPLAY_NAMES.get(t, t)
        td = topics.get(t)
        if td:
            lines.append(
                f"| {display} | {len(td.entities)} | {len(td.principles)} "
                f"| {len(td.methods)} | {len(td.metrics)} |\n"
            )
        else:
            lines.append(f"| {display} | 0 | 0 | 0 | 0 |\n")
    lines.append("\n")

    # --- Key BOUNDED-BY chains (top 15 across all topics) ---
    bounded = []
    for td in topics.values():
        for rel, path in td.relations:
            if rel.get("predicate") == "BOUNDED-BY":
                bounded.append((rel, path, td.topic))
    if bounded:
        lines.append("## Top BOUNDED-BY Chains\n\n")
        lines.append("| Subject | → | Limiting Principle | Topic | Source |\n")
        lines.append("|---------|---|-------------------|-------|--------|\n")
        for rel, path, topic in sorted(bounded, key=lambda x: x[0].get("subject", ""))[:20]:
            subj = _md_escape(rel.get("subject", "?"))
            obj = _md_escape(rel.get("object", "?"))
            display_topic = TOPIC_DISPLAY_NAMES.get(topic, topic)
            label = _paper_label(path)
            lines.append(f"| `{subj}` | BOUNDED-BY | `{obj}` | {display_topic} | {label} |\n")
        lines.append("\n")

    return "".join(lines)


def build_topic_index(td: TopicData, repo: Path) -> str:
    display = TOPIC_DISPLAY_NAMES.get(td.topic, td.topic)
    lines = [HEADER]
    lines.append(f"# {display} — Topic Index\n\n")
    lines.append(f"> Auto-generated {_timestamp()} · {td.paper_count} papers · {td.node_count} nodes · {td.relation_count} relations\n\n")

    # --- Entities ---
    if td.entities:
        lines.append("## Entities\n\n")
        lines.append("| ID | Name | Level | Source |\n")
        lines.append("|----|------|------:|--------|\n")
        for ent, path in sorted(td.entities, key=lambda x: x[0].get("id", "")):
            eid = _md_escape(ent.get("id", "?"))
            name = _truncate(ent.get("name", "—"), 60)
            level = ent.get("hierarchy_level", "—")
            label = _paper_label(path)
            rel_path = _relative_paper_path(path, repo)
            lines.append(f"| `{eid}` | {name} | {level} | [{label}]({rel_path}) |\n")
        lines.append("\n")

    # --- Principles ---
    if td.principles:
        lines.append("## Principles\n\n")
        lines.append("| ID | Name | Tier | Source |\n")
        lines.append("|----|------|------|--------|\n")
        for pri, path in sorted(td.principles, key=lambda x: x[0].get("id", "")):
            pid = _md_escape(pri.get("id", "?"))
            name = _truncate(pri.get("name", "—"), 60)
            tier = _md_escape(str(pri.get("tier", "—")))
            label = _paper_label(path)
            rel_path = _relative_paper_path(path, repo)
            lines.append(f"| `{pid}` | {name} | {tier} | [{label}]({rel_path}) |\n")
        lines.append("\n")

    # --- Methods ---
    if td.methods:
        lines.append("## Methods\n\n")
        lines.append("| ID | Name | Source |\n")
        lines.append("|----|------|--------|\n")
        for meth, path in sorted(td.methods, key=lambda x: x[0].get("id", "")):
            mid = _md_escape(meth.get("id", "?"))
            name = _truncate(meth.get("name", "—"), 60)
            label = _paper_label(path)
            rel_path = _relative_paper_path(path, repo)
            lines.append(f"| `{mid}` | {name} | [{label}]({rel_path}) |\n")
        lines.append("\n")

    # --- Metrics ---
    if td.metrics:
        lines.append("## Metrics\n\n")
        lines.append("| ID | Name | Best Value | Source |\n")
        lines.append("|----|------|------------|--------|\n")
        for met, path in sorted(td.metrics, key=lambda x: x[0].get("id", "")):
            mid = _md_escape(met.get("id", "?"))
            name = _truncate(met.get("name", "—"), 50)
            val, _ = _get_demonstrated_value(met)
            label = _paper_label(path)
            rel_path = _relative_paper_path(path, repo)
            lines.append(f"| `{mid}` | {name} | {_truncate(val, 60)} | [{label}]({rel_path}) |\n")
        lines.append("\n")

    # --- BOUNDED-BY chains ---
    bounded = [
        (rel, path)
        for rel, path in td.relations
        if rel.get("predicate") == "BOUNDED-BY"
    ]
    if bounded:
        lines.append("## BOUNDED-BY Chains\n\n")
        for rel, path in sorted(bounded, key=lambda x: x[0].get("id", "")):
            rid = rel.get("id", "?")
            subj = rel.get("subject", "?")
            obj = rel.get("object", "?")
            label = _paper_label(path)
            lines.append(f"### `{rid}`: `{subj}` → `{obj}`\n\n")
            lines.append(f"- **Source**: {label}\n")
            bps = rel.get("breakthrough_paths")
            if bps and isinstance(bps, list):
                lines.append("- **Breakthrough paths**:\n")
                for bp in bps:
                    direction = bp.get("direction", "?")
                    status = bp.get("status", "?")
                    gain = bp.get("expected_gain", "")
                    line = f"  - `{direction}` — status: {status}"
                    if gain:
                        line += f" · gain: {_truncate(str(gain), 60)}"
                    lines.append(line + "\n")
            lines.append("\n")

    # --- Cross-topic references ---
    # Collect all node IDs defined in this topic
    local_ids: set[str] = set()
    for ent, _ in td.entities:
        if ent.get("id"):
            local_ids.add(ent["id"])
    for pri, _ in td.principles:
        if pri.get("id"):
            local_ids.add(pri["id"])
    for meth, _ in td.methods:
        if meth.get("id"):
            local_ids.add(meth["id"])
    for met, _ in td.metrics:
        if met.get("id"):
            local_ids.add(met["id"])

    # Find references to external IDs in this topic's relations
    external_refs: list[tuple[str, str, str, str]] = []  # (rel_id, predicate, ext_id, source)
    for rel, path in td.relations:
        for field in ("subject", "object"):
            ref_id = rel.get(field, "")
            if ref_id and ref_id not in local_ids and "." in ref_id:
                external_refs.append(
                    (rel.get("id", "?"), rel.get("predicate", "?"), ref_id, _paper_label(path))
                )

    if external_refs:
        lines.append("## Cross-Topic References\n\n")
        lines.append("Nodes referenced but not defined in this topic:\n\n")
        lines.append("| Relation | Predicate | External Node | Source |\n")
        lines.append("|----------|-----------|---------------|--------|\n")
        seen = set()
        for rid, pred, ext_id, src in sorted(external_refs, key=lambda x: x[2]):
            key = (ext_id, pred, src)
            if key in seen:
                continue
            seen.add(key)
            lines.append(f"| `{rid}` | {pred} | `{ext_id}` | {src} |\n")
        lines.append("\n")

    return "".join(lines)


def build_metrics_index(topics: dict[str, TopicData], all_topic_names: list[str], repo: Path) -> str:
    lines = [HEADER]
    lines.append("# 📊 Metrics Quick Reference\n\n")
    lines.append(f"> Auto-generated {_timestamp()}\n\n")

    for t in all_topic_names:
        td = topics.get(t)
        if not td or not td.metrics:
            continue
        display = TOPIC_DISPLAY_NAMES.get(t, t)
        lines.append(f"## {display}\n\n")
        lines.append("| ID | Name | Best Value | Conditions | Source |\n")
        lines.append("|----|------|------------|------------|--------|\n")
        for met, path in sorted(td.metrics, key=lambda x: x[0].get("id", "")):
            mid = _md_escape(met.get("id", "?"))
            name = _truncate(met.get("name", "—"), 45)
            val, cond = _get_demonstrated_value(met)
            label = _paper_label(path)
            rel_path = _relative_paper_path(path, repo)
            lines.append(
                f"| `{mid}` | {name} | {_truncate(val, 60)} "
                f"| {_truncate(cond, 50)} | [{label}]({rel_path}) |\n"
            )
        lines.append("\n")

    return "".join(lines)


def build_principles_index(topics: dict[str, TopicData], all_topic_names: list[str], repo: Path) -> str:
    lines = [HEADER]
    lines.append("# 🔬 Principles Quick Reference\n\n")
    lines.append(f"> Auto-generated {_timestamp()}\n\n")

    # Collect all principles with tier info
    by_tier: dict[str, list[tuple[dict, Path, str]]] = defaultdict(list)
    for t in all_topic_names:
        td = topics.get(t)
        if not td:
            continue
        for pri, path in td.principles:
            tier = str(pri.get("tier", "unspecified")).lower()
            by_tier[tier].append((pri, path, t))

    # Output grouped by tier in canonical order
    ordered_tiers = [t for t in TIER_ORDER if t in by_tier]
    remaining = [t for t in sorted(by_tier) if t not in TIER_ORDER]
    ordered_tiers.extend(remaining)

    for tier in ordered_tiers:
        items = by_tier[tier]
        lines.append(f"## Tier: {tier}\n\n")
        lines.append("| ID | Name | Topic | Source |\n")
        lines.append("|----|------|-------|--------|\n")
        for pri, path, topic in sorted(items, key=lambda x: x[0].get("id", "")):
            pid = _md_escape(pri.get("id", "?"))
            name = _truncate(pri.get("name", "—"), 55)
            display_topic = TOPIC_DISPLAY_NAMES.get(topic, topic)
            label = _paper_label(path)
            rel_path = _relative_paper_path(path, repo)
            lines.append(f"| `{pid}` | {name} | {display_topic} | [{label}]({rel_path}) |\n")
        lines.append("\n")

    return "".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Auto-generate INDEX files from YAML source of truth."
    )
    parser.add_argument(
        "--repo-path",
        type=Path,
        default=Path("."),
        help="Root of the sci-logic-kb repository (default: current dir)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be generated without writing files",
    )
    args = parser.parse_args()
    repo: Path = args.repo_path.resolve()

    # Load data
    papers = load_all_papers(repo)
    topics = aggregate(papers)
    all_topic_names = discover_topic_dirs(repo)

    # Ensure empty topics appear
    for t in all_topic_names:
        if t not in topics:
            topics[t] = TopicData(t)

    # Build outputs
    outputs: list[tuple[Path, str]] = []

    # 1. Root INDEX.md
    outputs.append((repo / "INDEX.md", build_root_index(topics, all_topic_names, repo)))

    # 2. Per-topic INDEX.md
    for t in all_topic_names:
        td = topics[t]
        topic_index_path = repo / "topics" / t / "INDEX.md"
        outputs.append((topic_index_path, build_topic_index(td, repo)))

    # 3. INDEX_metrics.md
    outputs.append((repo / "INDEX_metrics.md", build_metrics_index(topics, all_topic_names, repo)))

    # 4. INDEX_principles.md
    outputs.append((repo / "INDEX_principles.md", build_principles_index(topics, all_topic_names, repo)))

    # Write or dry-run
    for path, content in outputs:
        if args.dry_run:
            print(f"[DRY-RUN] Would write {path} ({len(content)} chars)")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"Wrote {path} ({len(content)} chars)")

    total_nodes = sum(td.node_count for td in topics.values())
    total_rels = sum(td.relation_count for td in topics.values())
    print(f"\nDone: {len(papers)} papers, {total_nodes} nodes, {total_rels} relations across {len(all_topic_names)} topics.")


if __name__ == "__main__":
    main()
